### ISSUE TITLE
[ HELP ] Error while trying to run this example 

### ISSUE THREAD

**Issue by abhi18av** [wwiill/jwe-auth#1]
Hi @wwiill 

I was trying to experiment with the `jwe-auth` repo to explore whether a combination of `pedestal` with `buddy` could be ideal for a project I'm doing but when I try to `lein run` the demo, I get the following error 

```

Abhinavs-MacBook-Pro:jwe-auth eklavya$ lein run
Exception in thread "main" java.lang.RuntimeException: could not start [#'jwe-auth.pedestal/service-map] due to, compiling:(/private/var/folders/gz/sdxvfmgd0_38g225sldvm7j00000gn/T/form-init7034282020889623371.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: could not start [#'jwe-auth.pedestal/service-map] due to
	at mount.core$up$fn__280.invoke(core.cljc:92)
	at mount.core$up.invokeStatic(core.cljc:92)
	at mount.core$up.invoke(core.cljc:90)
	at mount.core$bring.invokeStatic(core.cljc:242)
	at mount.core$bring.invoke(core.cljc:234)
	at mount.core$start.invokeStatic(core.cljc:284)
	at mount.core$start.doInvoke(core.cljc:276)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at jwe_auth.core$_main.invokeStatic(core.clj:8)
	at jwe_auth.core$_main.doInvoke(core.clj:6)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:377)
	at user$eval160.invokeStatic(form-init7034282020889623371.clj:1)
	at user$eval160.invoke(form-init7034282020889623371.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at jwe_auth.pedestal$pedestal_config.invokeStatic(pedestal.clj:17)
	at jwe_auth.pedestal$pedestal_config.invoke(pedestal.clj:12)
	at jwe_auth.pedestal$eval19081$fn__19082.invoke(pedestal.clj:21)
	at mount.core$record_BANG_.invokeStatic(core.cljc:86)
	at mount.core$record_BANG_.invoke(core.cljc:85)
	at mount.core$up$fn__280.invoke(core.cljc:93)
	... 28 more


```

Could you please help me out a bit ?

**Comment by wwiill** [comment]
I believe you need an environment variable eg. PORT=3000

**Comment by abhi18av** [comment]
Ah, yes this worked :)
